Feature/pass inventory to exploration
Haje-Guildmaster/guildmaster pull request #12
Opened 2021-01-10 15:21 UTC by Jaewookim08

- ExplorationPreparer를 추가하여 탐색 준비 총괄&준비 취소 기능 추가.
- 선택된 인벤토리를 ExplorationLoader로 전달
- 탐색 준비 윈도우들의 서로에 대한 의존성 제거. async/await을 이용하여 선택값을 반환하기까지를 책임으로 함.
- 선택된 캐릭터가 0명일 경우 돌려보내기
- 기타 도구 추가/수정.
- 기타 버그 수정.

2021-01-13 14:57 UTC, honeyirene requested changes

2021-01-13 14:57 UTC, honeyirene commented on Assets/Scripts/TownRoam/ExplorationPreparer.cs
> +                            case 0:
이부분 숫자로 되어있어서 가독성이 안좋은데 step을 enum으로 만들고 매번 바꿔주는게 좋을듯?
```
step = MyEnum.MyPhase
```

2021-01-13 15:00 UTC, honeyirene commented
기존 PR 하고 충돌해서 rebase 해주심 좋을듯

2021-01-13 15:09 UTC, Jaewookim08 commented on Assets/Scripts/TownRoam/ExplorationPreparer.cs
> +                            case 0:
네

2021-01-23 14:34 UTC, Jaewookim08 commented
Rebase --onto 하고 int step 대신 enum과 goto case로 바꿨습니다.

2021-02-11 14:13 UTC, merged