Character
Haje-Guildmaster/guildmaster pull request #13
Opened 2021-01-24 01:14 UTC by adlet0331

캐릭터 스텟 변경 PR

2021-01-29 05:25 UTC, Jaewookim08 requested changes
리뷰했습니다. 너무 늦어서 죄송..

2021-01-29 05:25 UTC, Jaewookim08 commented on Assets/Scripts/Characters/Character.cs
> +        public List<Trait> ActiveTraits => StaticData.BasicData.ActiveTraits;       // 캐릭터 특성
(옛날 코드긴 한데) 변경 불가능한 리스트는 IReadOnlyList로 주면 좋을 듯

2021-01-29 05:25 UTC, Jaewookim08 commented on Assets/Scripts/Characters/Character.cs
> +                if (value < 1) return;
조건에 따라 아무 일도 안 하는 건 꽤나 이해하기 힘든 버그의 원인이 될 수 있음. 차라리 에러를 던지는 편이 좋아 보임

2021-01-29 05:25 UTC, Jaewookim08 commented on Assets/Scripts/Characters/Character.cs
> +        }
change계열 변수를 다 public으로 풀어 버린다면 이 변수의 올바른 값을 유지시킬 수 있을지에 대해 조금 걱정되긴 한다.
뭐 본인이 생각하는 구조가 있을거라 생각함

2021-01-29 05:25 UTC, Jaewookim08 commented on Assets/Scripts/Characters/Character.cs
> +                }
한번에 레벨이 2 이상 증가하는 경우가 고려되지 않음

2021-01-29 05:25 UTC, Jaewookim08 commented on Assets/Scripts/Characters/Character.cs
>              set => _loyalty.Value = Math.Min(MaxLoyalty, Math.Max(value, 0));
의도를 모르겠을 뿐더러 property를 사용하는 사람이 생각할 동작과 굉장히 차이가 있어 보임.

2021-01-29 05:25 UTC, Jaewookim08 commented on Assets/Scripts/Characters/CharacterStatData.cs
> +        public int MaxLevel;
unity에서 readonly array를 편집할 수 없으니 배열이 가변 길이가 되는 건 custom inspector를 직접 짜지 않는 이상 필연적이긴 하나, 그럼 위 리스트들이 MaxLevel만큼의 길이가 안 될 때 시작하자마자 에러를 던지는 정도의 안전장치가 있으면 좋을 것 같음. Serialization callback이나 character 생성자에서?
안 그러면 특정 캐릭터가 일정 이상 레벨에 올랐을 때만 발동하는 애매한 에러가 나올 만 하니.

2021-01-29 05:25 UTC, Jaewookim08 commented on Assets/Scripts/Exploration/EventsLogic/ExpressionProcessor.cs
> +                        //변경 필요
Todo로 표시해 주세요.
+클래스를 변경할 일이 생겼을 때 그 클래스를 사용하는 곳을 일일이 바꾸는 것도 방법 중 하나지만 기존에 있던 함수(Atk, Agi)등을 Obsolete로 표시만 해 두고   남겨 두는 것도 괜찮은 방법 중 하나. 또는 그 함수들을 불렀을 때 에러를 날리던가.

2021-01-29 05:25 UTC, Jaewookim08 commented on Assets/Scripts/Exploration/ExplorationView/UI/Footer/FooterCharacterInfo.cs
> +                //스텟 수정중이라 잠시 꺼두기
이제 이 주석은 지워야 할 듯?

2021-02-01 07:09 UTC, adlet0331 commented on Assets/Scripts/Characters/Character.cs
> +        public List<Trait> ActiveTraits => StaticData.BasicData.ActiveTraits;       // 캐릭터 특성
Trait List 를 Readonly로 바꿨어요

2021-02-01 07:10 UTC, adlet0331 commented on Assets/Scripts/Characters/Character.cs
> +                if (value < 1) return;
1보다 작거나 MaxLevel 보다 높게 set 되려면 Error 던지게 해뒀어요

2021-02-01 07:11 UTC, adlet0331 commented on Assets/Scripts/Characters/Character.cs
> +                }
수정했어요

2021-02-01 07:12 UTC, adlet0331 commented on Assets/Scripts/Characters/Character.cs
>              set => _loyalty.Value = Math.Min(MaxLoyalty, Math.Max(value, 0));
이건 기획이 (내부적인 값 -> 표시되는 값) 이걸 0 ->0, 1~10 -> 1 이런 식으로 표시되게 하면 좋겠다고 해서 이렇게 구현을 했어요

2021-02-01 07:12 UTC, adlet0331 commented on Assets/Scripts/Characters/Character.cs
>              set => _loyalty.Value = Math.Min(MaxLoyalty, Math.Max(value, 0));
코드상으로 조금 더 디테일을 주석으로 달아놔야겠네요

2021-02-01 07:13 UTC, adlet0331 commented on Assets/Scripts/Exploration/EventsLogic/ExpressionProcessor.cs
> +                        //변경 필요
Expression.CharacterStatus 수정해놨습니다.

2021-02-01 07:56 UTC, Jaewookim08 requested changes
ㅁㄴㅇㄹ
+CharacterStatData에 MaxLevel만큼의 길이가 안 되는 배열 찾는 안전장치 만들어 달라는 것도 안 되어 있어요

2021-02-01 07:56 UTC, Jaewookim08 commented on Assets/Scripts/Characters/Character.cs
> +                }
여전히 문제 있어 보여.
_xp.Value = value - LevelupXP[_level];가 아니라
value -= LevelupXP[_level];이어야 할 것 같아.

2021-02-01 07:56 UTC, Jaewookim08 commented on Assets/Scripts/Characters/Character.cs
>              set => _loyalty.Value = Math.Min(MaxLoyalty, Math.Max(value, 0));
그렇다고 하더라도 get과 set은 일관성 있는 행동을 해야 한다고 생각해. 이 프로퍼티를 쓰는 사람은 대충 이름만 보고 변수와 비슷한 행동양상을 보일 것이라 생각할 테니.
예를 들어 _loyalty가 5인데, Loyalty += 3을 썼을 때 _loyalty가 (3+9)/10+3 = 4가 되어 오히려 줄어드는 건 보통 뜻밖의 결과로 받아들여질 거 아냐?
Loyalty property를 내부적인 값으로만 쓰고 GetLoyaltyDisplayedValue 라는 함수(또는 property)를 추가하던가 Loyalty를 get만 남겨 두고 SetLoyaltyInnerValue를 추가한다던가 하는 식으로 내부값/표시값의 접근 방식을 다르게 하는 게 좋다고 본다.

2021-02-01 08:36 UTC, adlet0331 commented on Assets/Scripts/Characters/Character.cs
> +                }
그러네요

2021-02-01 08:40 UTC, adlet0331 commented on Assets/Scripts/Characters/Character.cs
>              set => _loyalty.Value = Math.Min(MaxLoyalty, Math.Max(value, 0));
분리했어요. Summary로 사용법을 적어뒀습니다

2021-02-01 10:00 UTC, Jaewookim08 approved these changes

2021-02-01 10:21 UTC, merged