인벤토리 데이터구조 개편, 아이템 창 구현
Haje-Guildmaster/guildmaster pull request #4
Opened 2020-10-05 11:25 UTC by adlet0331

Intentory 데이터구조 개편(Dictionary -> List Array
아이템을 보여주는 ItemWindow와 InventoryWindow 분리 및 완성
탐험 아이템 선택 창, 간단한 월드맵(기능 구현 X) 구현

2020-10-05 11:53 UTC, Jaewookim08 commented on Assets/Scripts/Data/Inventory.cs
> +        }
그냥 Item과 ItemNum 변수를 public으로 푸는 것과 차이가 없는 것 같습니다.

2020-10-05 14:43 UTC, Jaewookim08 commented
ExplorationCharacterSelectingWindow.cs.meta랑 ExplorationItemSelectingWindow.cs.meta가 깃에 포함 안된듯

2020-10-06 19:01 UTC, Jaewookim08 requested changes
잘 짰다고 생각합니다. 제가 좀 깐깐하게 코멘트를 달긴 했는데, 대부분 큰 문제가 있는 거라기보다는 이렇게 하면 더 깔끔하지 않을까- 에 가까운 내용입니다. 다만 역할 구분이 불명확하거나 맡은 책임이 너무 많은 객체들이 많이 보입니다. 조금 더 객체들의 책임과 의존성에 신경 써서 고쳐 주었으면 합니다.

2020-10-06 19:01 UTC, Jaewookim08 commented on Assets/Scripts/Data/Inventory.cs
> +        public int TotalSize => totalsize;
Auto-Implemented Properties을 사용하면 더 좋을 것 같습니다.

2020-10-06 19:01 UTC, Jaewookim08 commented on Assets/Scripts/Data/Inventory.cs
> +    }
그냥 Item과 ItemNum 변수를 public으로 푸는 것과 차이가 없는 것 같습니다.

2020-10-06 19:01 UTC, Jaewookim08 commented on Assets/Scripts/Data/Inventory.cs
> +        public Inventory(int _WindowSize, int _TotalSize, bool _IsStacked)
클래스 내부의 변수명과 겹치는 게 문제라면 this. 으로 구분할 수 있습니다.

2020-10-06 19:01 UTC, Jaewookim08 commented on Assets/Scripts/GameInput.cs
>                  }
UiWindowsManager.CloseSingleWindow 같은 함수 만들어서 거기로 옮겨주세요. 윈도우가 닫히는 순서는 그쪽 책임입니다.

2020-10-06 19:01 UTC, Jaewookim08 commented on Assets/Scripts/GameInput.cs
> +                UiWindowsManager.Instance.itemInfoPanel.Close(ItemIcon.panelRequestId); // 마우스 올리고 I 누르면 pannel이 안 꺼져서 추가함. 아래도 동일한 이유
InventoryWindow가 처리해야 하는 내용. Issues에 추가하면 수정하겠습니다. GameInput이 해결해야 하는 문제는 아니므로 원래대로 돌려주세요.

2020-10-06 19:01 UTC, Jaewookim08 commented on Assets/Scripts/Windows/Inventory/InventoryWindow.cs
>          }
ChangeCategory 왜 이렇게 코드를 이상하게 짰나 하고 보니까 제 코드네요.
수정하겠습니다....

2020-10-06 19:01 UTC, Jaewookim08 commented on Assets/Scripts/Windows/ItemWindow.cs
> +    private void InitiateIcons()
InitializeIcons를 잘못 쓴 듯?

2020-10-06 19:01 UTC, Jaewookim08 commented on Assets/Scripts/Windows/ItemWindow.cs
> +            _ItemIconList[i].UpdateAppearance(null, 0, i, _inventory, this);
Instantiate의 반환값을 이용해 UpdateAppearance를 부르는 게 낫습니다. 방금 생성한 itemIcon을 i번째 요소가 일 것이라고 생각하고 진행하는 것은 이 경우엔 틀리진 않았습니다만 에러가 나기 쉽고 보기에 직관적이지도 않습니다. 아니면 아예 전부 추가한 후에 밑에 foreach를 하나 더 넣어 UpdateAppearance를 부르는 것도 좋습니다.

2020-10-06 19:01 UTC, Jaewookim08 commented on Assets/Scripts/Data/Inventory.cs
> +        public Inventory(int _WindowSize, int _TotalSize, bool _IsStacked)
Inventory는 이상한 점이 좀 많습니다. 일단 WindowSize와 TotalSize를 받는다는 게 조금은 이상하게 느껴집니다 . _TotalSize를 WindowSize로 나누어서 category 개수가 자유롭게 결정되는데(_TotalSize가 WindowSize의 배수가 아니면 _TotalSize가 total size가 아니게 되기도 하고요), 밑에 getItemToCategoryNum을 보면 category는 제한되어 있어야 합니다. AddItem에서는 카테고리 분류 기능이 Inventory에 있지만 ChangeItemIndex는 caller쪽에서 아이템의 카테고리를 구한 뒤에 불러야 한다는 것도 이상합니다. 그러니까 코드 일부는 카테고리가 딱 일정 종류에 한정되어 있고 인벤토리가 알아서 처리해 줄 것처럼 되어 있으면서 일부는 category가 그냥 int 사이즈 값인 것처럼 짜여 있습니다. 인벤토리가 꼭 여러 카테고리를 다 담아야 할까요? 카테고리 관련 코드를 빼면 훨씬 클래스가 깔끔해질 것 같습니다.

2020-10-06 19:01 UTC, Jaewookim08 commented on Assets/Scripts/Windows/ExplorationCharacterSelectingWindow.cs
> +            if(first) Set_allCharacters();
첫 번째 열릴 때만 allCharacters를 설정하는 것 같은데 그러면 안 되지 않나 생각합니다.

2020-10-06 19:01 UTC, Jaewookim08 commented on Assets/Scripts/Windows/ExplorationCharacterSelectingWindow.cs
> +        }
이 클래스가 다음 행동을 결정하지 말고, 선택한 캐릭터들을 반환하는 것 까지를 역할로 하면 더 좋을 것 같습니다.
그나저나 선택한 캐릭터들은 외부에서 어떻게 가져오는 거죠?

2020-10-06 19:01 UTC, Jaewookim08 commented on Assets/Scripts/Windows/ExplorationItemSelectingWindow.cs
> +        }
마찬가지로, 다음/뒤로가기를 얘가 직접 처리하는 것보다 유저가 어떤 선택을 했는지와 선택한 아이템들을 반환하는 것까지를 역할로 하면 좋을 것 같습니다.

2020-10-06 19:01 UTC, Jaewookim08 commented on Assets/Scripts/Windows/Inventory/ItemIcon.cs
> +        private static int _panelRequestId;
static이면 안 되는 변수인데 어째서 변경했나요?

2020-10-06 19:01 UTC, Jaewookim08 commented on Assets/Scripts/Windows/Inventory/ItemIcon.cs
> +            //���� - �κ��丮 �� ��ȣ�ۿ�� ��� ¥��� �ߴ� ����. �ϴ� �κ��丮 - �κ��丮 or ���� - ���� ��ȣ�ۿ븸 ������
인코딩이 utf-8이 아닌 것으로 보입니다.

2020-10-06 19:01 UTC, Jaewookim08 commented on Assets/Scripts/Windows/Inventory/ItemIcon.cs
> +    public class ItemIcon : GenericButton<int>, IPointerEnterHandler, IPointerExitHandler, IDragHandler, IBeginDragHandler, IEndDragHandler, IDropHandler
부속품으로 쓰이는 오브젝트인데, 너무 맡는 역할이 많습니다.(재사용을 힘들게 합니다. ItemIcon을 사용하는 모든 상황이 이 기능들을 다 사용한다는 보장이 없으니까요:) ) 사실 그렇게 따지면 원래 제가 짠 패널 띄우는 코드도 여기에 있으면 안되긴 하네요. 여하튼 활용성을 높이려면 최대한 객체의 책임을 간단하게 하는 것이 좋습니다.

2020-10-06 19:01 UTC, Jaewookim08 commented on Assets/Scripts/Windows/Inventory/ItemIcon.cs
> +        public void UpdateAppearance(Item item, int number, int index, Data.Inventory inventory, ItemWindow itemWindow)
ItemWindow에 대한 의존성은 넘어간다 치더라도 Inventory에 의존하는 건 문제가 좀 있습니다.

2020-10-06 19:01 UTC, Jaewookim08 commented on Assets/Scripts/Windows/Inventory/ItemIcon.cs
> +            ItemWindow.DraggingItem = this;
이 정도로 구현 깊숙이 있는 클래스에서 ItemWindow의 누구나 변경 가능한 static 변수를 조작하는 건 상당히 예측하기 어렵고 에러나기 쉬운 동작입니다.

2020-10-06 19:01 UTC, Jaewookim08 commented on Assets/Scripts/Windows/ItemWindow.cs
> +    public static ItemIcon DraggingItem;
public static 변수를 최대한 피합시다.

2020-10-06 19:01 UTC, Jaewookim08 commented on Assets/Scripts/Windows/ItemWindow.cs
> +public class ItemWindow : MonoBehaviour
ItemIcon과 똑같이, 너무나 많은 역할을 맡은 클래스입니다.(재사용이 사실상 불가능해졌습니다) 사실 SetInventory(inventory) 함수로써 보여주는 아이템을 결정하는데 동작은 Player.Instance.Inventorys나 ...ExplorationItemSelectingWindow.ExploreInventory를 접근해서 한다는 것부터 무언가 심각하게 문제가 있습니다. 역할을 인벤토리를 보여주는 것 정도로 한정시켜 놓고 OnClick 등은 이벤트를 통해 위(클래스의 사용자)로 올려보내면 어떨까요.

2020-10-07 11:00 UTC, adlet0331 reviewed
구현 전 피드백

2020-10-07 11:00 UTC, adlet0331 commented on Assets/Scripts/Data/Inventory.cs
> +        public Inventory(int _WindowSize, int _TotalSize, bool _IsStacked)
인벤토리 하나를 상정하고 만든 코드라, 탐색에 가져갈 Bag같은 곳에서는 편법을 사용하여 구현한 점이 있습니다. (무조건 카테고리를 0으로 설정)

2020-10-07 11:00 UTC, adlet0331 commented on Assets/Scripts/Data/Inventory.cs
> +        public Inventory(int _WindowSize, int _TotalSize, bool _IsStacked)
생각해보니 카테고리를 빼고 Inventory 위에 PlayerInventory를 만드는게 훨씬 괜찮을 것 같네요. 일단 그렇게 방향을 잡고 고쳐보겠습니다.
인벤토리를 하나에 담으려는 프레임에 갇혀있었던 것 같습니다.

2020-10-07 11:00 UTC, adlet0331 commented on Assets/Scripts/Windows/ExplorationCharacterSelectingWindow.cs
> +        }
리스트를 public으로 할 생각입니다.

2020-10-07 11:00 UTC, adlet0331 commented on Assets/Scripts/Windows/ExplorationCharacterSelectingWindow.cs
> +            if(first) Set_allCharacters();
allCharacters, exploreCharacters 둘 다 public으로 수정하고 Awake에서 allCharacters를 초기화하도록 하겠습니다.

2020-10-07 11:00 UTC, adlet0331 commented on Assets/Scripts/Windows/ExplorationCharacterSelectingWindow.cs
> +            if(first) Set_allCharacters();
그나저나 마을->탐색->마을로 씬이동이 된다면 2번째 마을 씬으로 갈 때 Awake가 또 불러와지나요? 그렇게 되면 탐색씬에서 탐색을 간 길드원들을 넘겨받아야 할 것 같네요.

2020-10-07 11:00 UTC, adlet0331 commented on Assets/Scripts/Windows/ExplorationItemSelectingWindow.cs
> +        }
위와 마찬가지로 리스트를 Public으로 선언을 하겠습니다.

2020-10-07 11:00 UTC, adlet0331 commented on Assets/Scripts/Windows/Inventory/ItemIcon.cs
> +        public void UpdateAppearance(Item item, int number, int index, Data.Inventory inventory, ItemWindow itemWindow)
Drag Drop 기능 구현하면서 추가한 코드입니다. 
인벤토리에서 가방으로 옮기는 기능을 추가하려 추가했었는데, 이건 클릭 이벤트로 대체되어서 inventory 의존성 부분은 완전히 삭제하겠습니다.

2020-10-07 11:00 UTC, adlet0331 commented on Assets/Scripts/Windows/Inventory/ItemIcon.cs
> +            ItemWindow.DraggingItem = this;
새로운 클래스를 둬서 싱글톤화 시키고, public 변수로 선언하도록 변경해보겠습니다.

2020-10-07 11:00 UTC, adlet0331 commented on Assets/Scripts/Windows/ItemWindow.cs
> +public class ItemWindow : MonoBehaviour
그렇게 변경해보겠습니다.

2020-10-07 11:00 UTC, adlet0331 commented on Assets/Scripts/Windows/ItemWindow.cs
> +    public static ItemIcon DraggingItem;
이것 또한 새로운 클래스를 둬서 싱글톤화 시키고, public 변수로 선언하도록 변경해보겠습니다.

2020-10-07 11:00 UTC, adlet0331 commented on Assets/Scripts/Windows/ItemWindow.cs
> +            _ItemIconList[i].UpdateAppearance(null, 0, i, _inventory, this);
foreach문을 추가하겠습니다.

2020-10-07 11:00 UTC, adlet0331 commented on Assets/Scripts/Windows/ExplorationCharacterSelectingWindow.cs
> +            if(first) Set_allCharacters();
네 파괴가 되었다가 다시 생성된다고 하네요.

2020-10-26 14:44 UTC, adlet0331 reviewed
에러 고치는 것과 이벤트 처리만 남았습니다

2020-11-02 10:49 UTC, adlet0331 reviewed
일단은 완료했어요.

이벤트 구독이 겹치는 문제만 해결하면 진짜 끝.

2020-11-04 13:36 UTC, honeyirene requested changes
전반적으로 namespace 많이 빠져있던데 다 넣어주세요

2020-11-04 13:36 UTC, honeyirene commented on Assets/Scripts/Data/Inventory.cs
> +        public ItemStack(Item _item, int _itemnum)
ItemStack이 사실상 Inventory class 에서만 쓰이는데
비슷한 구조 다른 쪽에서 만들게 된다면 메인 class 안에 넣어서 private으로 바꾸는게 좋을거 같아요

2020-11-04 13:36 UTC, honeyirene commented on Assets/Scripts/GameInput.cs
>              //Settings 와 그 자식 파일들
위에 처럼 exploration 창 여는 키라고 주석 넣어주세요 👍

2020-11-04 13:36 UTC, honeyirene commented on Assets/Scripts/Data/Inventory.cs
> +        public Inventory(int _WindowSize, int _TotalSize, bool _IsStacked)
Inventory 를 Inventory랑 Inventroy entry 등 좀 개념상 나누는게 좋을거같고 size관련 문제는 window 즉 UI 쪽 코드에서 처리하는게 맞을거같아요 
Inventory를 아이템을 받고 넘기고, 어떤 템을 가지고 있는지, 최대치에 걸리지는 않는지 등등. 데이터 관리를 핵심으로 작성하고 그에 필요한 부가 기능들을 다른 클래스 (Inventory entry나 InventoryWindow 등등)로 쪼개는게 맞을거같네요

2020-11-04 13:36 UTC, honeyirene commented on Assets/Scripts/Data/Player.cs
> +        public readonly PlayerInventory PlayerInventory;
이름 고민해봅시다

2020-11-04 13:36 UTC, honeyirene commented on Assets/Scripts/Data/Inventory.cs
>  namespace GuildMaster.Data
namespace 연습

2020-11-04 13:36 UTC, honeyirene commented on Assets/Scripts/Data/Inventory.cs
> +        }
이 함수를 inventory로 옮기고 정리해주세요

2020-11-04 13:36 UTC, honeyirene commented on Assets/Scripts/Data/Inventory.cs
> +        }
```
        private void setItemStack(Item item, int itemNum, int idx)
        {
            if (item == (Item)null && itemNum != 0)
            {
                throw new ArgumentException("������ ���� null�Դϴ�");
            }
            _inventoryList[idx].Item = item;
            _inventoryList[idx].ItemNum = itemNum;
        }
```

2020-11-04 13:36 UTC, honeyirene commented on Assets/Scripts/Data/Inventory.cs
> +        }
1. inventory에서 stack 직접 조작하도록 변경하기
2. if 랑 for 중괄호

2020-11-04 13:36 UTC, honeyirene commented on Assets/Scripts/Windows/Inventory/ItemIcon.cs
> +
한줄 지워주세요

2020-11-04 13:36 UTC, honeyirene commented on Assets/Scripts/Windows/Inventory/ItemListView.cs
> +    [SerializeField] public ItemIcon ItemIconPrefab;
namespace 지정 해주세요

2020-11-04 13:36 UTC, honeyirene commented on Assets/Scripts/Windows/Inventory/ItemListView.cs
> +            _ItemIconList[_index].ItemIconOnOff(onoff);
중괄호

2020-11-04 13:36 UTC, honeyirene commented on Assets/Scripts/Windows/Inventory/ItemListView.cs
> +        Bag,
중괄호

2020-11-09 14:05 UTC, adlet0331 reviewed
PR 일차 완료

2020-11-10 04:10 UTC, honeyirene approved these changes

2020-11-10 05:43 UTC, Jaewookim08 approved these changes
리뷰 마무리하겠습니다.
+ namespace Inventory만 클래스 이름이랑 안 겹치게 좀 해주세요

2020-11-10 11:56 UTC, merged